# Script to produce the plots for the Week 1 assignment of the EDA module

# N.B. Lines 6:41 set up the data and should only need to
#       execute once - the plot is generated by line 42 onward

# This line can be edited as appropriate
setwd("d:/Ian/git/datasciencecoursera/ExData_Plotting1")
# Download and unzip the data if they are not already in the working directory
if (!file.exists("household_power_consumption.zip")) {
    fileurl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
    setInternet2(use = TRUE)
    err <- download.file(fileurl, destfile = "household_power_consumption.zip",
                         mode = "wb")
    if (err > 0) {
        return(print(paste("Download failed; error code:",err)))
    } else {
        downloaddate <- date()
        unzip("household_power_consumption.zip", junkpaths = TRUE)
    }
    rm(fileurl, err)
}
# If not done, read and subset the data and convert to appropriate classes
if (!file.exists("household_power_consump_tidy.txt")) {
    data <- read.csv2("household_power_consumption.txt", na.strings = "?",
       colClasses = "character")
    data$Date2 <- as.Date(data$Date, format="%d/%m/%Y")
    # subset
    data <- data[data$Date2 == "2007-02-01" | data$Date2 == "2007-02-02", ]
    data$Time <- strptime(paste(data$Date, data$Time), format = "%d/%m/%Y %T")
    # replace the original Date with the converted one
    data <- data[, -1]
    colnames(data)[colnames(data) == "Date2"] <- "Date"
    data <- data[, c(9, 1:8)]
    # convert the remaining columns to reals
    data[, 3:9] <- sapply(data[, 3:9], as.numeric)
    write.csv(data, "household_power_consump_tidy.txt", row.names=FALSE)
} else {
    data <- read.csv("household_power_consump_tidy.txt")
    data$Time <- strptime(data$Time, format="%Y-%m-%d %H:%M:%S")
    data$Date <- as.Date(data$Date, format="%Y-%m-%d")
}
# Produce the plot
ylimit <- max(data[,7:9])
png("plot3.png")
with(data, plot(Time, Sub_metering_1, type = "l", axes = FALSE,
                ylab="", xlab="", ylim = c(0,ylimit),))
par(new = TRUE)
with(data, plot(Time, Sub_metering_2, type = "l", axes = FALSE,
                ylab="", xlab="", ylim = c(0,ylimit), col = "red"))
par(new = TRUE)
with(data, plot(Time, Sub_metering_3, type = "l", ylab = "Energy sub metering",
                xlab="", ylim = c(0,ylimit), col = "blue"))
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2",
       "Sub_metering_3"), lty = 1, col = c(1,2,4))
dev.off()
